### PR TITLE
Fix kernel close and select bug

### LINKED ISSUE #48: Fix select syscall
Currently passing an empty fdset/None to select syscall could cause a panic. The source of the panic comes from 
```
let (writenfd, mut real_writefds) = selectbittables[1].get(&FDKIND_KERNEL).unwrap();
```
in select_syscall of net_calls.rs.
I traced a little bit deeper, and it looks like in ```get_bitmask_for_select```, it will return an empty HashMap if the fdset is empty or None. Then since the HashMap is empty, when it calls get(&FDKIND_KERNEL), that would return None, and the following unwrap would cause panic.

### PR DESCRIPTION
**Pull request by Yaxuan-w**
## Description

Fixes #48 

 

#### kernel close
The updated fdtable API passing fd entry and count instead of real fd into `kernel_close` function in RawPOSIX, which will cause the actual requested real fd not being closed. Updated code to fit newest API.

#### select
The initial error occurred because cases where each `fd_set` was empty were not handled. In the updated code, uninitialized values are automatically assigned to the corresponding `fd_set`. Additionally, during in-depth debugging, I found that when processing the return value, the `fdtable::` function should receive an `nfd` associated with the kernel file descriptor (i.e., the maximum kernel file descriptor + 1).

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [socketselect.c](https://github.com/Lind-Project/lind_project/blob/develop/tests/test_cases/socketselect.c)
- [uds-nb-select.c](https://github.com/Lind-Project/lind_project/blob/develop/tests/test_cases/uds-nb-select.c)
- [uds-socketselect.c](https://github.com/Lind-Project/lind_project/blob/develop/tests/test_cases/uds-socketselect.c)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

### CODE REVIEW

File: src/safeposix/syscalls/net_calls.rs [hunk 1]
```diff
@@ -509,7 +502,6 @@ impl Cage {
         mut errorfds: Option<&mut fd_set>,
         rposix_timeout: Option<RustDuration>,
     ) -> i32 {
-
```
Comment (JustinCappos) [inline src/safeposix/syscalls/net_calls.rs:512]: Shouldn't be changed

File: src/safeposix/syscalls/net_calls.rs [hunk 2]
```diff
@@ -532,25 +524,36 @@ impl Cage {
         fdkindset.insert(FDKIND_KERNEL);
 
         let (selectbittables, unparsedtables, mappingtable) = fdtables::prepare_bitmasks_for_select(self.cageid, nfds as u64, orfds.copied(), owfds.copied(), oefds.copied(), &fdkindset).unwrap();
+
```
Comment (JustinCappos) [inline src/safeposix/syscalls/net_calls.rs:534]: Also, shouldn't be changed.

File: src/safeposix/syscalls/net_calls.rs [hunk 3]
```diff
@@ -532,25 +524,36 @@ impl Cage {
...
+        
         // libc select()
-        let (readnfd, mut real_readfds) = selectbittables[0].get(&FDKIND_KERNEL).unwrap();
-        let (writenfd, mut real_writefds) = selectbittables[1].get(&FDKIND_KERNEL).unwrap();
-        let (errornfd, mut real_errorfds) = selectbittables[2].get(&FDKIND_KERNEL).unwrap();
+        // Check: 
+        // 1. If there exists virtual fd_set values 
+        // 2. If there exists kernel fd_set
+        // If yes -- Convert into kernel fd_set structure
+        // If no -- Set it to null
```
Comment (JustinCappos) [inline src/safeposix/syscalls/net_calls.rs]: This is "what" you are doing.   Can you talk about "why" instead?

File: src/safeposix/syscalls/net_calls.rs [hunk 4]
```diff
@@ -560,14 +563,14 @@ impl Cage {
...
+        // let start_time = starttimer();
 
-        let end_time = match rposix_timeout {
-            Some(time) => time,
-            None => RustDuration::MAX,
-        };
+        // let end_time = match rposix_timeout {
+        //     Some(time) => time,
+        //     None => RustDuration::MAX,
+        // };
```
Comment (JustinCappos) [inline src/safeposix/syscalls/net_calls.rs]: Why are you leaving in commented code? (see other lines around this too)

File: src/safeposix/syscalls/net_calls.rs [hunk 5]
```diff
@@ -658,7 +661,7 @@ impl Cage {
         if let Some(errorfds) = errorfds.as_mut() {
             **errorfds = error_result.unwrap();
         }
-
```
Comment (JustinCappos) [inline src/safeposix/syscalls/net_calls.rs:661]: More random space changes.   You shouldn't be adding spaces.

**Review by JustinCappos — COMMENTED** [review]
Needs This review box is broken.   I can't see if I'm approving, but it should say that I requestchanges.

File: src/safeposix/syscalls/net_calls.rs (hunk 5 above)
Comment (Yaxuan-w) [reply src/safeposix/syscalls/net_calls.rs:661]: The space adjustments were intended to make the code a bit more readable and visually consistent, especially aligning it with the formatting in other system call implementations. I thought it might help with overall clarity, but I'm open to revisiting it if needed.

File: src/safeposix/syscalls/net_calls.rs (hunk 4 above)
Comment (Yaxuan-w) [reply src/safeposix/syscalls/net_calls.rs]: This is used for im-pipes. Currently we haven't added support of those sub-system but I've implemented the code logic for that in summer. I leave the code as commented so I could add the logic once we add the subsystem

File: src/safeposix/syscalls/fs_calls.rs [hunk 6]
```diff
@@ -1881,8 +1881,8 @@ impl Cage {
     }
 }
 
-pub fn kernel_close(_fdentry: fdtables::FDTableEntry, kernelfd: u64) {
+pub fn kernel_close(fdentry: fdtables::FDTableEntry, _count: u64) {
```
Comment (ChinmayShringi) [inline src/safeposix/syscalls/fs_calls.rs:1884]: Changing the var name from `kernelfd` to `_count` might be confusing

Comment (Yaxuan-w) [reply src/safeposix/syscalls/fs_calls.rs:1884]: > The updated fdtable API passing fd entry and count instead of real fd into kernel_close function in RawPOSIX

^ reason of changing the var's name

File: src/safeposix/syscalls/net_calls.rs (hunk 4 above)
Comment (rennergade) [reply src/safeposix/syscalls/net_calls.rs]: Yeah we should separate this out. Most of the pipe work we did this summer was more of a PoC, this stuff will have to be moved to a grate later I believe?
